export const states = {
    RUNNING: "RUNNING",
    SHORT_BREAK_RUNNING: "SHORT_BREAK_RUNNING",
    LONG_BREAK_RUNNING: "LONG_BREAK_RUNNING",
    IDLE: "IDLE",
    PAUSED: "PAUSED"
};

export const events = {
    START: "START",
    STOP: "STOP",
    CANCEL: "CANCEL",
    COMPLETE: "COMPLETE",
    PAUSE: "PAUSE",
    RESUME: "RESUME",

    SHORT_BREAK_START: "SHORT_BREAK_START",
    SHORT_BREAK_PAUSE: "SHORT_BREAK_PAUSE",
    SHORT_BREAK_RESUME: "SHORT_BREAK_RESUME",
    SHORT_BREAK_COMPLETE: "SHORT_BREAK_COMPLETE",
    SHORT_BREAK_CANCEL: "SHORT_BREAK_CANCEL",

    LONG_BREAK_START: "LONG_BREAK_START",
    LONG_BREAK_PAUSE: "LONG_BREAK_PAUSE",
    LONG_BREAK_RESUME: "LONG_BREAK_RESUME",
    LONG_BREAK_COMPLETE: "LONG_BREAK_COMPLETE",
    LONG_BREAK_CANCEL: "LONG_BREAK_CANCEL"
};
