module.exports.states = {
    RUNNING: "RUNNING",
    SHORT_BREAK_RUNNING: "SHORT_BREAK_RUNNING",
    LONG_BREAK_RUNNING: "LONG_BREAK_RUNNING",
    IDLE: "IDLE",
    PAUSED: "PAUSED"
};

module.exports.events = {
    START: "START",
    STOP: "STOP",
    CANCEL: "CANCEL",
    COMPLETE: "COMPLETE",
    PAUSE: "PAUSE",
    RESUME: "RESUME",

    SHORT_BREAK_START: "SHORT_BREAK_START",
    SHORT_BREAK_PAUSE: "SHORT_BREAK_PAUSE",
    SHORT_BREAK_RESUME: "SHORT_BREAK_RESUME",
    SHORT_BREAK_COMPLETE: "SHORT_BREAK_COMPLETE",
    SHORT_BREAK_CANCEL: "SHORT_BREAK_CANCEL",

    LONG_BREAK_START: "LONG_BREAK_START",
    LONG_BREAK_PAUSE: "LONG_BREAK_PAUSE",
    LONG_BREAK_RESUME: "LONG_BREAK_RESUME",
    LONG_BREAK_COMPLETE: "LONG_BREAK_COMPLETE",
    LONG_BREAK_CANCEL: "LONG_BREAK_CANCEL"
};

module.exports.defaults = {
    DEFAULT_BLOCK: 30,
    DEFAULT_LONG_BREAK: 15,
    DEFAULT_SHORT_BREAK: 5,
    DEFAULT_CLOCK_COLOR: "red",
};

